name: mern-app

services:
  server-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      - mongo

  client-app:
      build:
        context: ./client
        dockerfile: Dockerfile
      restart: unless-stopped
      volumes:
        - ./client:/app
        - /app/node_modules
      networks:
        - mern-app
      ports:
        - 3000:3000
      command: npm run dev -- --host
      depends_on:
        - server-api

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge
